# Generated by Django 5.2.8 on 2026-01-13 21:10

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasDiarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, unique=True)),
                ('total_deposito_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_deposito_qtd', models.IntegerField(default=0)),
                ('total_saque_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_saque_qtd', models.IntegerField(default=0)),
                ('total_bonus_concedido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_apostado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_premios', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('house_edge_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Lucro Bruto (GGR)')),
                ('novos_usuarios', models.IntegerField(default=0)),
                ('usuarios_ativos', models.IntegerField(default=0)),
                ('ftds_qtd', models.IntegerField(default=0, verbose_name='Qtd Primeiros Depósitos')),
                ('ftds_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('performance_modalidades', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Métrica Diária',
                'verbose_name_plural': 'Métricas Diárias',
                'get_latest_by': 'data',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True, verbose_name='CPF ou CNPJ')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='WhatsApp')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo em Conta')),
                ('recebeu_bonus', models.BooleanField(default=False)),
                ('meta_rollover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_apostado_rollover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('data_primeiro_deposito', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('conta_suspeita', models.BooleanField(default=False)),
                ('motivo_suspeita', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('SAQUE', 'Saque')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado/Falhou'), ('CANCELADO', 'Cancelado'), ('EM_ANALISE', 'Em Análise (Compliance)')], default='PENDENTE', max_length=20)),
                ('id_externo', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID da Transação na SkalePay')),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('risco_score', models.IntegerField(default=0, help_text='0-100. Acima de 80 bloqueia auto.')),
                ('analise_motivo', models.TextField(blank=True, help_text='Motivo da análise de risco', null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_financeiras', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APOSTA', 'Débito - Aposta'), ('PREMIO', 'Crédito - Prêmio'), ('DEPOSITO', 'Crédito - Depósito'), ('SAQUE', 'Débito - Saque'), ('ESTORNO', 'Crédito - Estorno'), ('BONUS', 'Crédito - Bônus')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('origem_solicitacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacao_efetivada', to='accounts.solicitacaopagamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extrato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
