# Generated by Django 5.2.8 on 2026-02-11 22:18

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True, verbose_name='CPF ou CNPJ')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='WhatsApp')),
                ('saldo', models.BigIntegerField(default=0, verbose_name='Saldo em Conta (Centavos)')),
                ('recebeu_bonus', models.BooleanField(default=False)),
                ('meta_rollover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_apostado_rollover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('data_primeiro_deposito', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('conta_suspeita', models.BooleanField(default=False)),
                ('motivo_suspeita', models.TextField(blank=True, null=True)),
                ('tipo_usuario', models.CharField(choices=[('JOGADOR', 'Jogador Comum'), ('AFILIADO', 'Afiliado'), ('ADMIN', 'Administrador')], default='JOGADOR', max_length=10)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('modo_comissao', models.CharField(choices=[('APOSTA', 'Ganha % por Aposta Feita'), ('DEPOSITO', 'Ganha % por Depósito Realizado')], default='APOSTA', max_length=10, verbose_name='Modo de Comissão')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('afiliado', models.ForeignKey(blank=True, db_column='afiliado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicados', to=settings.AUTH_USER_MODEL)),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MetricasDiarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, unique=True)),
                ('total_deposito_valor', models.BigIntegerField(default=0, verbose_name='Total Depositado (Centavos)')),
                ('total_deposito_qtd', models.IntegerField(default=0)),
                ('total_saque_valor', models.BigIntegerField(default=0, verbose_name='Total Sacado (Centavos)')),
                ('total_saque_qtd', models.IntegerField(default=0)),
                ('total_bonus_concedido', models.BigIntegerField(default=0, verbose_name='Total Bônus Concedido (Centavos)')),
                ('total_apostado', models.BigIntegerField(default=0, verbose_name='Total Apostado (Centavos)')),
                ('total_premios', models.BigIntegerField(default=0, verbose_name='Total Prêmios (Centavos)')),
                ('house_edge_valor', models.BigIntegerField(default=0, verbose_name='Lucro Bruto GGR (Centavos)')),
                ('novos_usuarios', models.IntegerField(default=0)),
                ('usuarios_ativos', models.IntegerField(default=0)),
                ('ftds_qtd', models.IntegerField(default=0, verbose_name='Qtd Primeiros Depósitos')),
                ('ftds_valor', models.BigIntegerField(default=0, verbose_name='Valor FTDs (Centavos)')),
                ('performance_modalidades', models.JSONField(blank=True, default=dict)),
                ('mapa_calor_horas', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Métrica Diária',
                'verbose_name_plural': 'Métricas Diárias',
                'get_latest_by': 'data',
                'indexes': [models.Index(fields=['data'], name='accounts_me_data_2651ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('SAQUE', 'Saque')], max_length=10)),
                ('valor', models.BigIntegerField(verbose_name='Valor (Centavos)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado/Falhou'), ('CANCELADO', 'Cancelado'), ('EM_ANALISE', 'Em Análise (Compliance)'), ('PROCESSANDO', 'Processando Pagamento')], default='PENDENTE', max_length=20)),
                ('id_externo', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID da Transação na SkalePay')),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave Pix')),
                ('risco_score', models.IntegerField(default=0, help_text='0-100. Acima de 80 bloqueia auto.')),
                ('analise_motivo', models.TextField(blank=True, help_text='Motivo da análise de risco', null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_financeiras', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APOSTA', 'Débito - Aposta'), ('PREMIO', 'Crédito - Prêmio'), ('DEPOSITO', 'Crédito - Depósito'), ('SAQUE', 'Débito - Saque'), ('ESTORNO', 'Crédito - Estorno'), ('BONUS', 'Crédito - Bônus'), ('COMISSAO', 'Crédito - Comissão')], max_length=10)),
                ('valor', models.BigIntegerField(verbose_name='Valor (Centavos)')),
                ('saldo_anterior', models.BigIntegerField(verbose_name='Saldo Anterior (Centavos)')),
                ('saldo_posterior', models.BigIntegerField(verbose_name='Saldo Posterior (Centavos)')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('origem_solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='accounts.solicitacaopagamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extrato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['cpf_cnpj'], name='accounts_cu_cpf_cnp_8ea4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['data_primeiro_deposito'], name='accounts_cu_data_pr_ec2179_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['tipo_usuario'], name='accounts_cu_tipo_us_74e4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['conta_suspeita'], name='accounts_cu_conta_s_e4289a_idx'),
        ),
    ]
