# Generated by Django 5.2.8 on 2025-12-23 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_remove_customuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APOSTA', 'Débito - Aposta'), ('PREMIO', 'Crédito - Prêmio'), ('DEPOSITO', 'Crédito - Depósito'), ('SAQUE', 'Débito - Saque'), ('ESTORNO', 'Crédito - Estorno')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extrato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
