# Generated by Django 5.2.8 on 2026-01-15 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_metricasdiarias_mapa_calor_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('JOGADOR', 'Jogador Comum'), ('CAMBISTA', 'Cambista'), ('ADMIN', 'Administrador')], default='JOGADOR', max_length=10),
        ),
    ]
