# Generated by Django 5.2.8 on 2026-01-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_comissao_percentual_customuser_gerente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('APOSTA', 'Débito - Aposta'), ('PREMIO', 'Crédito - Prêmio'), ('DEPOSITO', 'Crédito - Depósito'), ('SAQUE', 'Débito - Saque'), ('ESTORNO', 'Crédito - Estorno'), ('BONUS', 'Crédito - Bônus'), ('COMISSAO', 'Crédito - Comissão')], max_length=10),
        ),
    ]
