# Generated by Django 5.2.8 on 2025-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='meta_rollover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recebeu_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_apostado_rollover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
