# Generated by Django 5.2.8 on 2026-01-16 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_transacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='indicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicados', to=settings.AUTH_USER_MODEL, verbose_name='Indicado por (Promotor/Amigo)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='modo_comissao',
            field=models.CharField(choices=[('APOSTA', 'Ganha % por Aposta Feita'), ('DEPOSITO', 'Ganha % por Depósito Realizado')], default='APOSTA', max_length=10, verbose_name='Modo de Comissão'),
        ),
    ]
