# Generated by Django 5.2.8 on 2026-01-31 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_indicado_por_customuser_modo_comissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='indicado_por',
        ),
        migrations.AddField(
            model_name='customuser',
            name='afiliado',
            field=models.ForeignKey(blank=True, db_column='afiliado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('JOGADOR', 'Jogador Comum'), ('AFILIADO', 'Afiliado'), ('ADMIN', 'Administrador')], default='JOGADOR', max_length=10),
        ),
    ]
