# Generated by Django 5.2.8 on 2026-01-07 22:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_transacao_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasDiarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, unique=True)),
                ('total_deposito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_saque', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receita_liquida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_apostado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_premios', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('novos_usuarios', models.IntegerField(default=0)),
                ('usuarios_ativos', models.IntegerField(default=0)),
                ('ftds_qtd', models.IntegerField(default=0, verbose_name='Qtd Primeiros Depósitos')),
            ],
            options={
                'verbose_name': 'Métrica Diária',
                'verbose_name_plural': 'Métricas Diárias',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('SAQUE', 'Saque')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado/Falhou'), ('CANCELADO', 'Cancelado'), ('EM_ANALISE', 'Em Análise (Compliance)')], default='PENDENTE', max_length=20)),
                ('id_externo', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID da Transação na SkalePay')),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_financeiras', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transacao',
            name='origem_solicitacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacao_efetivada', to='accounts.solicitacaopagamento'),
        ),
    ]
