# Generated by Django 5.2.8 on 2026-01-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_indicado_por_customuser_afiliado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaopagamento',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix'),
        ),
    ]
