# Generated by Django 5.2.8 on 2026-01-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_solicitacaopagamento_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaopagamento',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave Pix'),
        ),
    ]
