# Generated by Django 5.2.8 on 2026-01-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_solicitacaopagamento_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaopagamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado/Falhou'), ('CANCELADO', 'Cancelado'), ('EM_ANALISE', 'Em Análise (Compliance)'), ('PROCESSANDO', 'Processando Pagamento')], default='PENDENTE', max_length=20),
        ),
    ]
