# Generated by Django 5.2.8 on 2026-02-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_transacao_origem_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='saldo',
            field=models.BigIntegerField(default=0, verbose_name='Saldo em Conta (Centavos)'),
        ),
        migrations.AlterField(
            model_name='solicitacaopagamento',
            name='valor',
            field=models.BigIntegerField(verbose_name='Valor (Centavos)'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='saldo_anterior',
            field=models.BigIntegerField(verbose_name='Saldo Anterior (Centavos)'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='saldo_posterior',
            field=models.BigIntegerField(verbose_name='Saldo Posterior (Centavos)'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.BigIntegerField(verbose_name='Valor (Centavos)'),
        ),
    ]
