# Generated by Django 5.2.8 on 2025-12-08 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicho',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('dezenas', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.CharField(choices=[('PTM', 'PTM - 11:30'), ('PT', 'PT - 14:30'), ('PTV', 'PTV - 16:30'), ('FED', 'Federal - 19:00'), ('COR', 'Corujinha - 21:30')], max_length=3)),
                ('fechado', models.BooleanField(default=False)),
                ('premio_1', models.CharField(blank=True, max_length=4, null=True)),
                ('premio_2', models.CharField(blank=True, max_length=4, null=True)),
                ('premio_3', models.CharField(blank=True, max_length=4, null=True)),
                ('premio_4', models.CharField(blank=True, max_length=4, null=True)),
                ('premio_5', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_jogo', models.CharField(choices=[('G', 'Grupo'), ('D', 'Dezena'), ('C', 'Centena'), ('M', 'Milhar'), ('MC', 'Milhar/Centena')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('palpite', models.CharField(max_length=4)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ganhou', models.BooleanField(default=False)),
                ('valor_premio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to=settings.AUTH_USER_MODEL)),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apostas', to='games.sorteio')),
            ],
        ),
    ]
