# Generated by Django 5.2.8 on 2026-02-11 22:18

import django.db.models.deletion
import games.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('loterias', 'Loterias'), ('bicho', 'Bicho'), ('loto', 'Loto')], default='bicho', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosDoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotacao_grupo', models.DecimalField(decimal_places=2, default=18.0, max_digits=6, verbose_name='Grupo (18x)')),
                ('cotacao_dezena', models.DecimalField(decimal_places=2, default=60.0, max_digits=6, verbose_name='Dezena (60x)')),
                ('cotacao_centena', models.DecimalField(decimal_places=2, default=600.0, max_digits=6, verbose_name='Centena (600x)')),
                ('cotacao_milhar', models.DecimalField(decimal_places=2, default=4000.0, max_digits=6, verbose_name='Milhar (4000x)')),
                ('cotacao_milhar_invertida', models.DecimalField(decimal_places=2, default=400.0, max_digits=6, verbose_name='Milhar Invertida')),
                ('cotacao_centena_invertida', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='Centena Invertida')),
                ('cotacao_duque_dezena', models.DecimalField(decimal_places=2, default=300.0, max_digits=6, verbose_name='Duque de Dezena')),
                ('cotacao_terno_dezena', models.DecimalField(decimal_places=2, default=3000.0, max_digits=6, verbose_name='Terno de Dezena')),
                ('cotacao_passe_vai_vem', models.DecimalField(decimal_places=2, default=40.0, max_digits=6, verbose_name='Passe Vai-Vem')),
                ('cotacao_milhar_centena', models.DecimalField(decimal_places=2, default=2000.0, max_digits=6, verbose_name='Milhar/Centena')),
                ('cotacao_duque_grupo', models.DecimalField(decimal_places=2, default=18.0, max_digits=6, verbose_name='Duque de Grupo')),
                ('cotacao_terno_grupo', models.DecimalField(decimal_places=2, default=150.0, max_digits=6, verbose_name='Terno de Grupo')),
                ('cotacao_quadra_grupo', models.DecimalField(decimal_places=2, default=1000.0, max_digits=6, verbose_name='Quadra de Grupo')),
                ('cotacao_quina_grupo', models.DecimalField(decimal_places=2, default=5000.0, max_digits=6, verbose_name='Quina de Grupo')),
                ('cotacao_passe_vai', models.DecimalField(decimal_places=2, default=80.0, max_digits=6, verbose_name='Passe Vai')),
                ('cotacao_quininha', models.JSONField(default=games.models.get_default_quininha, verbose_name="Tabela Quininha (Ex: {'1': 10, '5': 1000})")),
                ('cotacao_seninha', models.JSONField(default=games.models.get_default_seninha, verbose_name='Tabela Seninha')),
                ('cotacao_lotinha', models.JSONField(default=games.models.get_default_lotinha, verbose_name='Tabela Lotinha')),
                ('quininha_acertos_necessarios', models.IntegerField(default=1, verbose_name='Quininha (Acertos Min)')),
                ('seninha_acertos_necessarios', models.IntegerField(default=1, verbose_name='Seninha (Acertos Min)')),
                ('lotinha_acertos_necessarios', models.IntegerField(default=1, verbose_name='Lotinha (Acertos Min)')),
                ('modalidades_ativas', models.JSONField(blank=True, default=dict, help_text="Ex: {'M': true, 'G': false}", verbose_name='Modalidades Ativas (JSON)')),
                ('ativa_apostas', models.BooleanField(default=True)),
                ('milhar_brinde_ativa', models.BooleanField(default=False)),
                ('valor_minimo_para_brinde', models.BigIntegerField(default=0, verbose_name='Valor Mínimo para Brinde (Centavos)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do sorteio')),
                ('horario', models.CharField(blank=True, max_length=20, null=True)),
                ('fechado', models.BooleanField(default=False)),
                ('premio_1', models.CharField(blank=True, max_length=10, null=True)),
                ('premio_2', models.CharField(blank=True, max_length=10, null=True)),
                ('premio_3', models.CharField(blank=True, max_length=10, null=True)),
                ('premio_4', models.CharField(blank=True, max_length=10, null=True)),
                ('premio_5', models.CharField(blank=True, max_length=10, null=True)),
                ('resultado', models.JSONField(blank=True, help_text='Resultado bruto (JSON)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_palpites', models.IntegerField(default=1, help_text='Qtd números')),
                ('cotacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='games.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Colocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cotacao', models.DecimalField(decimal_places=2, help_text='Cotação específica desta colocação', max_digits=10)),
                ('mascara', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colocacoes', to='games.jogo')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colocacoes', to='games.modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BigIntegerField(verbose_name='Valor da Aposta (Centavos)')),
                ('palpites', models.JSONField(default=list)),
                ('comissao_gerada', models.BigIntegerField(default=0, verbose_name='Comissão Gerada (Centavos)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('sorteado', 'Sorteado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ganhou', models.BooleanField(default=False)),
                ('valor_premio', models.BigIntegerField(verbose_name='Valor do Prêmio (Centavos)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apostas', to=settings.AUTH_USER_MODEL)),
                ('colocacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.colocacao')),
                ('jogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apostas', to='games.jogo')),
                ('modalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apostas', to='games.modalidade')),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apostas', to='games.sorteio')),
            ],
            options={
                'db_table': 'palpite_aposta',
                'indexes': [models.Index(fields=['usuario', 'criado_em'], name='palpite_apo_usuario_08d0f6_idx'), models.Index(fields=['sorteio', 'status'], name='palpite_apo_sorteio_e40aae_idx'), models.Index(fields=['status', 'ganhou'], name='palpite_apo_status_4aeebd_idx')],
            },
        ),
    ]
