# Generated by Django 5.2.8 on 2025-12-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='palpite',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='tipo_jogo',
            field=models.CharField(choices=[('G', 'Grupo'), ('D', 'Dezena'), ('C', 'Centena'), ('M', 'Milhar'), ('MC', 'Milhar/Centena'), ('DG', 'Dupla de Grupo'), ('TG', 'Terno de Grupo'), ('QG', 'Quadra de Grupo'), ('QNG', 'Quina de Grupo'), ('DD', 'Duque de Dezena'), ('TD', 'Terno de Dezena'), ('PV', 'Passe Vai'), ('PVV', 'Passe Vai e Vem'), ('MI', 'Milhar Invertida'), ('CI', 'Centena Invertida'), ('DI', 'Dezena Invertida')], max_length=3),
        ),
    ]
