# Generated by Django 5.2.8 on 2025-12-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_aposta_palpite_alter_aposta_tipo_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='palpite',
            field=models.CharField(max_length=50),
        ),
    ]
