# Generated by Django 5.2.8 on 2025-12-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_aposta_palpite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosDoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotacao_grupo', models.DecimalField(decimal_places=2, default=18.0, max_digits=6, verbose_name='Grupo (18x)')),
                ('cotacao_dezena', models.DecimalField(decimal_places=2, default=60.0, max_digits=6, verbose_name='Dezena (60x)')),
                ('cotacao_centena', models.DecimalField(decimal_places=2, default=600.0, max_digits=6, verbose_name='Centena (600x)')),
                ('cotacao_milhar', models.DecimalField(decimal_places=2, default=4000.0, max_digits=6, verbose_name='Milhar (4000x)')),
                ('cotacao_milhar_centena', models.DecimalField(decimal_places=2, default=4400.0, max_digits=7, verbose_name='Milhar/Centena (4400x)')),
                ('premio_maximo_aposta', models.DecimalField(decimal_places=2, default=20000.0, help_text='Valor máximo que o sistema paga em uma única aposta.', max_digits=10, verbose_name='Teto Máximo (R$)')),
                ('ativa_apostas', models.BooleanField(default=True, verbose_name='Sistema Ativo?')),
            ],
            options={
                'verbose_name': 'Parâmetros do Jogo (Cotações)',
                'verbose_name_plural': 'Parâmetros do Jogo (Cotações)',
            },
        ),
    ]
