# Generated by Django 5.2.8 on 2026-01-06 23:18

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_parametrosdojogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_centena_invertida',
            field=models.DecimalField(decimal_places=2, default=800.0, max_digits=6, verbose_name='Centena Invertida'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_duque_grupo',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6, verbose_name='Duque de Grupo'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_milhar_invertida',
            field=models.DecimalField(decimal_places=2, default=8000.0, max_digits=7, verbose_name='Milhar Invertida'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_passe_vai',
            field=models.DecimalField(decimal_places=2, default=90.0, max_digits=6, verbose_name='Passe Vai'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_passe_vai_vem',
            field=models.DecimalField(decimal_places=2, default=45.0, max_digits=6, verbose_name='Passe Vai e Vem'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_quadra_grupo',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=6, verbose_name='Quadra de Grupo'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_quina_grupo',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=6, verbose_name='Quina de Grupo'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_terno_grupo',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=6, verbose_name='Terno de Grupo'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='lotinha_acertos_necessarios',
            field=models.IntegerField(default=5, help_text='Padrão: 5', verbose_name='Lotinha - Acertos p/ Ganhar'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='quininha_acertos_necessarios',
            field=models.IntegerField(default=5, help_text='Padrão: 5', verbose_name='Quininha - Acertos p/ Ganhar'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='seninha_acertos_necessarios',
            field=models.IntegerField(default=6, help_text='Padrão: 6', verbose_name='Seninha - Acertos p/ Ganhar'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='tabela_lotinha',
            field=models.JSONField(default=games.models.get_default_lotinha, verbose_name='Tabela Pagamento Lotinha'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='tabela_quininha',
            field=models.JSONField(default=games.models.get_default_quininha, verbose_name='Tabela Pagamento Quininha'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='tabela_seninha',
            field=models.JSONField(default=games.models.get_default_seninha, verbose_name='Tabela Pagamento Seninha'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='palpite',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='tipo_jogo',
            field=models.CharField(choices=[('G', 'Grupo'), ('D', 'Dezena'), ('C', 'Centena'), ('M', 'Milhar'), ('MC', 'Milhar/Centena'), ('DG', 'Dupla de Grupo'), ('TG', 'Terno de Grupo'), ('QG', 'Quadra de Grupo'), ('QNG', 'Quina de Grupo'), ('DD', 'Duque de Dezena'), ('TD', 'Terno de Dezena'), ('PV', 'Passe Vai'), ('PVV', 'Passe Vai e Vem'), ('MI', 'Milhar Invertida'), ('CI', 'Centena Invertida'), ('DI', 'Dezena Invertida'), ('MI', 'Milhar Invertida'), ('CI', 'Centena Invertida'), ('DI', 'Dezena Invertida'), ('QU', 'Quininha'), ('SE', 'Seninha'), ('LO', 'Lotinha')], max_length=3),
        ),
    ]
