# Generated by Django 5.2.8 on 2026-01-15 21:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_parametrosdojogo_cotacao_centena_invertida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='comissao_gerada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
