# Generated by Django 5.2.8 on 2026-01-16 21:46

import games.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_aposta_comissao_gerada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrosdojogo',
            options={'verbose_name': 'Parâmetros do Sistema', 'verbose_name_plural': 'Parâmetros do Sistema'},
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='cotacao_duque_grupo',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='cotacao_milhar_centena',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='cotacao_passe_vai',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='cotacao_quadra_grupo',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='cotacao_quina_grupo',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='cotacao_terno_grupo',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='lotinha_acertos_necessarios',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='premio_maximo_aposta',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='quininha_acertos_necessarios',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='seninha_acertos_necessarios',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='tabela_lotinha',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='tabela_quininha',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='tabela_seninha',
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_duque_dezena',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=6, verbose_name='Duque de Dezena'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_lotinha',
            field=models.JSONField(default=games.models.get_default_lotinha, verbose_name='Tabela Lotinha'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_quininha',
            field=models.JSONField(default=games.models.get_default_quininha, verbose_name="Tabela Quininha (Ex: {'1': 10, '5': 1000})"),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_seninha',
            field=models.JSONField(default=games.models.get_default_seninha, verbose_name='Tabela Seninha'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_terno_dezena',
            field=models.DecimalField(decimal_places=2, default=3000.0, max_digits=6, verbose_name='Terno de Dezena'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='limite_saque_automatico',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, verbose_name='Teto para Saque Automático (R$)'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='tempo_minimo_deposito_saque_minutos',
            field=models.IntegerField(default=120, verbose_name='Tempo Mínimo entre Depósito e Saque (min)'),
        ),
        migrations.AlterField(
            model_name='parametrosdojogo',
            name='cotacao_centena_invertida',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='Centena Invertida'),
        ),
        migrations.AlterField(
            model_name='parametrosdojogo',
            name='cotacao_milhar_invertida',
            field=models.DecimalField(decimal_places=2, default=400.0, max_digits=6, verbose_name='Milhar Invertida'),
        ),
        migrations.AlterField(
            model_name='parametrosdojogo',
            name='cotacao_passe_vai_vem',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=6, verbose_name='Passe Vai-Vem'),
        ),
    ]
