# Generated by Django 5.2.8 on 2026-01-16 23:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_parametrosdojogo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_milhar_brinde',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, verbose_name='Cotação da Milhar Brinde'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='milhar_brinde_ativa',
            field=models.BooleanField(default=False, verbose_name='Promoção Milhar Brinde Ativa?'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='modalidades_ativas',
            field=models.JSONField(blank=True, default=dict, help_text="Ex: {'M': true, 'G': false}", verbose_name='Modalidades Ativas (JSON)'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='valor_minimo_para_brinde',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10, verbose_name='Mínimo para ganhar Brinde (R$)'),
        ),
    ]
