# Generated by Django 5.2.8 on 2026-01-16 23:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_parametrosdojogo_cotacao_milhar_brinde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdojogo',
            name='premio_maximo_aposta',
            field=models.DecimalField(decimal_places=2, default=Decimal('20000.00'), max_digits=12, verbose_name='Prêmio Máximo por Aposta (R$)'),
        ),
    ]
