# Generated by Django 5.2.8 on 2026-01-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_parametrosdojogo_premio_maximo_aposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_duque_grupo',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=6, verbose_name='Duque de Grupo'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_milhar_centena',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=6, verbose_name='Milhar/Centena'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_passe_vai',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=6, verbose_name='Passe Vai'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_quadra_grupo',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=6, verbose_name='Quadra de Grupo'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_quina_grupo',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=6, verbose_name='Quina de Grupo'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='cotacao_terno_grupo',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=6, verbose_name='Terno de Grupo'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='lotinha_acertos_necessarios',
            field=models.IntegerField(default=1, verbose_name='Lotinha (Acertos Min)'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='quininha_acertos_necessarios',
            field=models.IntegerField(default=1, verbose_name='Quininha (Acertos Min)'),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='seninha_acertos_necessarios',
            field=models.IntegerField(default=1, verbose_name='Seninha (Acertos Min)'),
        ),
    ]
