# Generated by Django 5.2.8 on 2026-01-31 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_parametrosdojogo_cotacao_duque_grupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cotacao', models.DecimalField(decimal_places=2, help_text='Cotação específica desta colocação', max_digits=10)),
                ('mascara', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('loterias', 'Loterias'), ('bicho', 'Bicho'), ('loto', 'Loto')], default='bicho', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_palpites', models.IntegerField(default=1, help_text='Qtd números')),
                ('cotacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='games.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APOSTA', 'Débito - Aposta'), ('PREMIO', 'Crédito - Prêmio'), ('DEPOSITO', 'Crédito - Depósito'), ('SAQUE', 'Débito - Saque'), ('ESTORNO', 'Crédito - Estorno'), ('BONUS', 'Crédito - Bônus'), ('COMISSAO', 'Crédito - Comissão')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bicho',
        ),
        migrations.AlterModelOptions(
            name='parametrosdojogo',
            options={},
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='comissao_gerada',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='palpite',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='ativa_apostas',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='cotacao_milhar_brinde',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='limite_saque_automatico',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='milhar_brinde_ativa',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='premio_maximo_aposta',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='tempo_minimo_deposito_saque_minutos',
        ),
        migrations.RemoveField(
            model_name='parametrosdojogo',
            name='valor_minimo_para_brinde',
        ),
        migrations.RemoveField(
            model_name='sorteio',
            name='fechado',
        ),
        migrations.RemoveField(
            model_name='sorteio',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='sorteio',
            name='premio_1',
        ),
        migrations.RemoveField(
            model_name='sorteio',
            name='premio_2',
        ),
        migrations.RemoveField(
            model_name='sorteio',
            name='premio_3',
        ),
        migrations.RemoveField(
            model_name='sorteio',
            name='premio_4',
        ),
        migrations.RemoveField(
            model_name='sorteio',
            name='premio_5',
        ),
        migrations.AddField(
            model_name='aposta',
            name='palpites',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='aposta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('sorteado', 'Sorteado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='sorteio',
            name='resultado',
            field=models.JSONField(blank=True, help_text='Números sorteados (JSON)', null=True),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='tipo_jogo',
            field=models.CharField(choices=[('loterias', 'Loterias'), ('bicho', 'Bicho'), ('loto', 'Loto')], default='bicho', max_length=20),
        ),
        migrations.AlterField(
            model_name='sorteio',
            name='data',
            field=models.DateField(help_text='Data do sorteio'),
        ),
        migrations.AlterModelTable(
            name='aposta',
            table='palpite_aposta',
        ),
        migrations.AddField(
            model_name='aposta',
            name='colocacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.colocacao'),
        ),
        migrations.AddField(
            model_name='colocacao',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colocacoes', to='games.jogo'),
        ),
        migrations.AddField(
            model_name='colocacao',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colocacoes', to='games.modalidade'),
        ),
    ]
