# Generated by Django 5.2.8 on 2026-02-04 18:00

from django.db import migrations


def migrar_transacoes_games_para_accounts(apps, schema_editor):
    GamesTransacao = apps.get_model('games', 'Transacao')
    AccountsTransacao = apps.get_model('accounts', 'Transacao')

    batch = []
    for tx in GamesTransacao.objects.all().iterator(chunk_size=1000):
        batch.append(
            AccountsTransacao(
                usuario_id=tx.usuario_id,
                tipo=tx.tipo,
                valor=tx.valor,
                saldo_anterior=tx.saldo_anterior,
                saldo_posterior=tx.saldo_posterior,
                data=tx.data,
                descricao=tx.descricao,
            )
        )

        if len(batch) >= 1000:
            AccountsTransacao.objects.bulk_create(batch)
            batch = []

    if batch:
        AccountsTransacao.objects.bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_transacao_origem_solicitacao'),
        ('games', '0011_colocacao_jogo_modalidade_transacao_delete_bicho_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_transacoes_games_para_accounts, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
