# Generated by Django 5.2.8 on 2026-02-04 19:00

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_migrar_e_remover_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdojogo',
            name='ativa_apostas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='milhar_brinde_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parametrosdojogo',
            name='valor_minimo_para_brinde',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sorteio',
            name='horario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sorteio',
            name='fechado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sorteio',
            name='premio_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sorteio',
            name='premio_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sorteio',
            name='premio_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sorteio',
            name='premio_4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sorteio',
            name='premio_5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aposta',
            name='jogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apostas', to='games.jogo'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apostas', to='games.modalidade'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='tipo_jogo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aposta',
            name='palpite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aposta',
            name='comissao_gerada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
