# Generated by Django 5.2.8 on 2026-02-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_restore_fields_and_normalize_aposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteio',
            name='resultado',
            field=models.JSONField(blank=True, help_text='Resultado bruto (JSON)', null=True),
        ),
    ]
