# Generated by Django 5.2.8 on 2026-02-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_alter_sorteio_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='tipo_jogo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='valor',
            field=models.BigIntegerField(verbose_name='Valor da Aposta (Centavos)'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='valor_premio',
            field=models.BigIntegerField(verbose_name='Valor do Prêmio (Centavos)'),
        ),
        migrations.AlterField(
            model_name='parametrosdojogo',
            name='valor_minimo_para_brinde',
            field=models.BigIntegerField(default=0, verbose_name='Valor Mínimo para Brinde (Centavos)'),
        ),
    ]
